#!/usr/bin/env bash
# Generated by matugen — do not edit manually.
hyprctl eval 'hl.config({ general = { col = { active_border = { colors = {"rgba({{colors.primary.default.hex_stripped}}ee)", "rgba({{colors.tertiary.default.hex_stripped}}ee)"}, angle = 45 }, inactive_border = "rgba({{colors.outline.default.hex_stripped}}55)" } } })'
