# Generated by matugen — do not edit manually.
ZSH_BG1="{{colors.surface.default.hex}}"
ZSH_BG2="{{colors.surface_variant.default.hex}}"
ZSH_BG3="{{colors.secondary_container.default.hex}}"
ZSH_ACCENT="{{colors.primary.default.hex}}"
ZSH_FG="{{colors.on_surface.default.hex}}"
ZSH_FG_ON_ACCENT="{{colors.on_primary.default.hex}}"
