#!/usr/bin/env bash
# Generated by matugen — do not edit manually.
hyprctl eval 'hl.config({ general = { col = { active_border = { colors = {"rgba(abc7ffee)", "rgba(ddbce0ee)"}, angle = 45 }, inactive_border = "rgba(8e909955)" } } })'
