#!/usr/bin/env bash
# Generated by matugen — do not edit manually.
hyprctl eval 'hl.config({ general = { col = { active_border = { colors = {"rgba(e3c36cee)", "rgba(adcfaeee)"}, angle = 45 }, inactive_border = "rgba(98908055)" } } })'
