#!/usr/bin/env bash
# Generated by matugen — do not edit manually.
hyprctl eval 'hl.config({ general = { col = { active_border = { colors = {"rgba(f9ba72ee)", "rgba(bdcd9dee)"}, angle = 45 }, inactive_border = "rgba(9d8e8155)" } } })'
