wallpaper {
    monitor = HDMI-A-1
    path = /home/luca/Pictures/wallpaper/amber-island.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/luca/Pictures/wallpaper/amber-island.jpg
    fit_mode = cover
}

splash = false
ipc = true
