general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock screen after 10 minutes of idle
listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock
    on-resume = hyprctl dispatch dpms on
}

# Turn off displays after 15 minutes of idle
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
