" Basic Vim setup
syntax on
filetype plugin indent on

set number
set mouse=a
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set ignorecase
set smartcase
set incsearch
set hlsearch

" Use system clipboard if available/provider works
set clipboard=unnamedplus

" XDG-compliant data and state directories
set undodir=$XDG_DATA_HOME/vim/undo//
set directory=$XDG_DATA_HOME/vim/swap//
set backupdir=$XDG_DATA_HOME/vim/backup//
let &viminfofile = $XDG_STATE_HOME . '/vim/viminfo'
let g:netrw_home = $XDG_DATA_HOME . '/vim'

silent! call mkdir(&undodir, 'p')
silent! call mkdir(&directory, 'p')
silent! call mkdir(&backupdir, 'p')
silent! call mkdir(fnamemodify(&viminfofile, ':h'), 'p')
